### ISSUE TITLE
Alda was not found on your $PATH.

### ISSUE THREAD

**Issue by Conaws** [jgkamat/alda-mode#3]
Getting this error when trying to use Alda in emacs, but able to run the alda repl just fine
Alda appears in my usr/local/bin and that is on my class path

Any idea whats up?

**Comment by jgkamat** [comment]
My best guess is that the $PATH that emacs sees is not the same one as the shell. Try running 
`M-x eval-expression<RET> (shell-command-to-string "echo $PATH")`
and see if that command's output includes /usr/local/bin. If not, you probably need to run `export PATH` in a shell and restart Emacs. (and you probably should put `export PATH` in .profile after you set it as well :smile:). I'm guessing in your bashrc you have something like `PATH=<stuff>` but it's never exported, so only your shell gets that change.

However, I'm going to add a variable that you can set to override the alda path (which would guarantee that it works). I'll close this issue once I've implemented that.

Just curious, what system are you running this on? I haven't tested this on mac (but should work?), and this won't work on windows (unless you installed emacs in cygwin).

**Comment by jgkamat** [comment]
You should be able to now add 
`(setq alda-binary-location "/usr/local/bin/alda")`
after updating to the latest version (after it's built on melpa) to make it work regardless.

Let me know if it dosent work, and thanks for using alda-mode (and alda)! Let me know if you find any other issues, this is pretty new software (and I'm new to emacs dev).

**Comment by Conaws** [comment]
Not getting the same error, but now getting 'Alda server is down', any idea?

**Comment by Conaws** [comment]
yeah, just had to rtfm to discover that you need to start a alda server before you could run in emacs.  Still, worth mentioning in readme that that's how it works -- or in error message

**Comment by jgkamat** [comment]
`alda-play-region` should automatically start a alda server in emacs if one is not started. Was the error message "Alda server down, starting in Emacs." or just "Alda server is down"? Essentially, All I do is run alda commands. If the alda server is down, they automatically start an alda server for you (inside of emacs). What version of alda are you using, I've only tested on `1.0.0 RC>6`.

Starting the alda server externally should solve this problem, but the feature is intended to start it for you if not already started (it may take a while to start up though). I'd rather solve the problem than adjust the docs if possible.

**Comment by Conaws** [comment]
Message was Alda server is down, starting in emacs, but that didn't start
the server.

After running Alda server in terminal other commands worked

On Friday, March 18, 2016, Jay Kamat notifications@github.com wrote:

> alda-mode should automatically start a alda server in emacs if one is not
> started. Was the error message "Alda server down, starting in Emacs." or
> just "Alda server is down"? Essentially, All I do is run alda commands. If
> the alda server is down, they automatically start an alda server for you.
> What version of alda are you using?
> 
> Starting the alda server externally should solve this problem, but the
> feature is intended to start it for you if not already done.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jgkamat/alda-mode/issues/3#issuecomment-198398353

## 

Sent from Gmail Mobile

**Comment by jgkamat** [comment]
which operating system are you using, and which alda version?

 when printing that message, I simply run the same command that I would normally run, except I append a infinite loop to keep the server from exiting (and alda starts the server automatically). Maybe I should use nohup instead, but I'm not sure if that would work as well. The reason for the infinite loop is that emacs kills the enclosing process (and the alda server) otherwise, which leads to not hearing any sound. I'm not sure if theres a way to keep a background process running en emacs but I'll look more closely.

**Comment by Conaws** [comment]
Mac OSX, latest Alda version

On Saturday, March 19, 2016, Jay Kamat notifications@github.com wrote:

> which operating system are you using, and which alda version?
> 
> when printing that message, I simply run the same command that I would
> normally run, except I append a infinite loop to keep the server from
> exiting (and alda starts the server automatically). Maybe I should use
> nohup instead, but I'm not sure if that would work as well.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jgkamat/alda-mode/issues/3#issuecomment-198750957

## 

Sent from Gmail Mobile

**Comment by jgkamat** [comment]
I've just updated alda-mode to try to simplify the starting of the emacs server. If updating dosen't solve your problem, could you run 
`(progn (start-process-shell-command "alda" "*output*" "alda server") (start-process-shell-command "alda" "*output*" "sleep 10 && alda play --code \"piano:ab>cdefga\""))` with `eval-expression`?

with the alda server DOWN and let me know what happens?

**Comment by jgkamat** [comment]
It's been a long time and alda mode's method of playback has changed a lot, so I'm closing this issue. If anyone sees this issue, please either reopen this issue or create a new one, and I'll get on it!
